### PR TITLE
Jarno/enhancement/131-team-page-enhancement-3

### PR DESCRIPTION
**Pull request by Rutjake**
Team member logos will enlarge when clicked and return to their original size when clicked again.
Added media query for smaller screens (padding) to avoid the enlarged logo going partially off screen.
The text in the member task section has been made slightly smaller for better visibility.

closes 131

## 🔧 **Changes Made**

1. [Briefly describe changes you made]
Added useState for click handling and added css rules for text and logo

2. [Any refactoring or clean-up tasks]

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]

https://github.com/user-attachments/assets/46078366-111a-4ef5-b455-d861dc6d1cf7

https://github.com/user-attachments/assets/5959983b-e8f1-4c12-9487-0e3265d83046

- **Known Issues**: [List any known issues or limitations]
Implementing Directus changed the page layout for some reason. So it may be necessary to make a new issue for adjusting the text spacing vertically to clarify the content on the page. Not included in this issue and may require larger changes elsewhere in the code.

### CODE REVIEW

**Comment by leolabdev** [comment]
@Rutjake Does this work well on mobile phones too?

**Comment by Rutjake** [comment]
I can only test it in a simulation (browser) because the data retrieval doesn't work if I test it on my phone for some reason. Responsiveness works in the browser.

**Review by Skoivumaki — CHANGES_REQUESTED** [review]
Logos are way too small when enlargened on mobile devices, tablet and desktop are fine.
Maybe 2x or 3x logo size on small devices?
image
Very intresting choice of resolution and crop on your example videos :D

**Comment by leolabdev** [comment]
@Rutjake @Skoivumaki  I had to merge (since they want the update before 18.12), but you can continue working on this branch. Also, consider adjusting the spacing between texts, headings, and so on.
image

**Pull request merged**
