### PR TITLE
93-update-navbar-path-and-make-comingSoonPage

### PR DESCRIPTION
**Pull request by Jonroi**
Update Navbar and Links
Add Coming Soon Page

### CODE REVIEW

**Review by leolabdev — CHANGES_REQUESTED** [review]
- [ ] I think we should not have an external 'Coming Soon' page from a UI/UX point of view.  I think it would be better to add a banner with specific information related to its own specific page. For example news page could contain: News page is under construction, coming soon. It would also be nice if the banner could offer to return to the previous page from which the user came.

- [x] We have a problem with the current number of elements not fitting on the page in some cases. I think we should think about how to reduce the number of topics and not touch the code  
image

- [ ] Why ? Are you sure this is needed here? Should an average user know the internal processes?  
image

- [ ]  Also, in my opinion, it is a very bad ux/ui that the user clicks on the navbar and gets to some external resources. This is not at all expected behavior and it is difficult to distinguish when we remain inside the application and when we do not.
This includes: "development", "education package", "past versions apk", "join us", "forum"
We need to avoid this as much as possible, and if not, think about how to indicate to the user that he is leaving the site

**Review by leolabdev — CHANGES_REQUESTED** [review]
- [x] nested elements should not extend beyond their line 

image

- [ ] Can we remove this solution from this branch for now? (everywhere except navbar)
image

**Comment by Jonroi** [comment]
Wierd I thought I fixed this yesterday to include only on navbar. I'll check this soon as possible

> * [ ]  nested elements should not extend beyond their line
> 
> image
> 
> * [ ]  Can we remove this solution from this branch for now? (everywhere except navbar)
>   image

**Comment by leolabdev** [comment]
> * [x]  nested elements should not extend beyond their line
> 
> image
> 
> * [x]  Can we remove this solution from this branch for now? (everywhere except navbar)
>   image



- [ ] the "problem nested elements should not extend beyond their line" is still exist 

image

**Comment by leolabdev** [comment]
maybe we could make the sidebar wider, and when it doesn't fit on mobile, reduce the font a bit

**Review by leolabdev — APPROVED** [review]
good job

**Pull request merged**
