### PR TITLE
jarno/enhancement/159-navbar-dropdown-animation

### PR DESCRIPTION
**Pull request by Rutjake**
Issue #159

## 🔧 **Changes Made**
1. Added transform and transition to Dropdown Wrapper for dropdown animation.

2. Removed a couple of lines from the .dropdownContent.closed class to make the dropdown closing animation.

---

## ✅ **Checklist Before Submission**

I have tested my code, and it works as expected.
No `console.log()` or other debugging statements are left.
Removed commented-out or unnecessary code.

---

## 📝 **Additional Information**

Provide any additional context or information that reviewers may need to know:

- **Screenshots**: [Include any screenshots or videos if the changes affect the UI]

https://github.com/user-attachments/assets/17f534f4-d652-4bf7-9190-a0521b63a4b9

### CODE REVIEW

**Review by Jonroi — APPROVED** [review]
Everything looks good and works as expected. The dropdown feels a bit fast for me, but let's see what others think. We can always tweak it later if needed.

**Comment by leolabdev** [comment]
I like the idea that you made a video, I'll test the animation locally and then make a decision

**Review by leolabdev — CHANGES_REQUESTED** [review]
The animation speed is ok, but check what happens to the sidebar now
image

**Comment by Rutjake** [comment]
Ok, I'll have to check what's causing it

ma 21. lokak. 2024 klo 14.43 Leo Hannolainen ***@***.***>
kirjoitti:

**Comment by Rutjake** [comment]
Somehow I didn't notice that mobile menu issue, now it should work.

**Review by Skoivumaki — COMMENTED** [review]
Mobile sidebars dropdowns now prone to breaking like so:
https://gyazo.com/542306238401078363af3b363575b748
This bug seems to only happen if user scrolls down in the sidebar. (which is inevitable since sometimes sidebar content overflows)

**Review by Skoivumaki — APPROVED** [review]
Mobile Scroll bug is fixed.
Added `@media` rules seem to not cause issues. Tested between screen width of 1023-1025px.

**Comment by leolabdev** [comment]
@Rutjake I had to change the implementation of your solution a little and create a new branch, can you please make a new PR from it, and also correct the animations I added. The new branch is "jarno/enhancement/159-navbar-dropdown-animation-3"

**Comment by leolabdev** [comment]
New branch, because we had a conflict with the dev, and I couldn't resolve it successfully =(

**Comment by leolabdev** [comment]
@Rutjake waiting for the new pr from the new branch

**Pull request closed without merging**
