### PR TITLE
juho/refactor/212-add-getters-for-app-paths

### PR DESCRIPTION
**Pull request by juho236**
## 📄 **Pull Request Overview**

**Issue Number**: [#212]

## 🔧 **Changes Made**

added getter functions to RoutePaths

replaced all cases of RoutePaths and AppRoutesLink with getter functions

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **JSDoc**: I have added or updated JSDoc comments for all relevant code.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.

---

## 📝 **Additional Information**

kept old list for compability

tested most of the links, but some pages were unused or had no links to them anywhere in the project

### CODE REVIEW

**Review by leolabdev — CHANGES_REQUESTED** [review]
Great job on organizing the route functions! 

To further improve adherence to the Single Responsibility Principle (SRP), please refactor functions like getNewsPageRoute, getHeroPageRoute, and getClansPageRoute, which currently handle both the base route and specific item routes. By separating these into individual functions—one for the base route and another for routes with a specific identifier—we can make each function’s purpose more explicit and improve maintainability.

Thank you for the hard work!

**Review by leolabdev — CHANGES_REQUESTED** [review]
Sorry for not saying it right away, I noticed another thing. It seems to me that the naming method described in the issue is more convenient. The getRoute...[someRoutername] pattern can help to immediately understand that the getter refers to the router and will not be confused with other possible getters during searching

**Comment by juho236** [comment]
Took a lot of copy and pasting, but it's done now

**Comment by leolabdev** [comment]
thanks!

**Review by leolabdev — APPROVED** [review]

**Pull request merged**
