### PR TITLE
jarno/enhancement/159-navbar-dropdown-animation-3

### PR DESCRIPTION
**Pull request by Rutjake**
Issue #159

## 🔧 **Changes Made**

Added transform-origin and Transform scaleY() to DropdownWrapper to adjust dropdown animation.

---

## ✅ **Checklist Before Submission**

I have tested my code, and it works as expected. (Desktop and Mobile, Assuming we add the same animation to the mobile version.)

---

## 📝 **Additional Information**

Desktop:

https://github.com/user-attachments/assets/f2363f67-ae04-45db-9a5d-ba4bb48855ca

Mobile:

https://github.com/user-attachments/assets/44f1b79b-203d-484d-b30b-c638230fc90c

### CODE REVIEW

**Comment by leolabdev** [comment]
I don't quite like how it looks on the Mobile when we collapse.

**Comment by Jonroi** [comment]
I think this is good for now? Let's take feedback and then we'll see if it needs adjusting or any new designs

**Comment by Skoivumaki** [comment]
> Good job. But, I don't quite like how it looks on the Mobile when we collapse =( or may be it is okay for now @Jonroi @Skoivumaki ?

I think it looks a bit weird upon collapsing. Theres smooth animations for it closing but collapses entirely in 1 frame when animation is done. Cant really describe it...

**Comment by leolabdev** [comment]
@Skoivumaki @Jonroi  Can you open an issue with a note that we won't touch it for now?

**Pull request merged**
