### PR TITLE
kaisa/enhancement/195-add-i18n-to-usedeleteclan

### PR DESCRIPTION
**Pull request by kaisahakola**
## 📄 **Pull Request Overview**

**Issue Number**: #195 

## 🔧 **Changes Made**

1. Added i18n to useDeleteClan

---

## ✅ **Checklist Before Submission**

- **Functionality**: I have tested my code, and it works as expected.
- **Debugging**: No `console.log()` or other debugging statements are left.
- **Clean Code**: Removed commented-out or unnecessary code.

---

### CODE REVIEW

**Review by Skoivumaki — APPROVED** [review]
i18n should work.
Note: Theres currently no way to test this since useDeleteClan is not yet implemented and probably wont even work. (API requires clan admin permissions and nothing in code checks for it atm)

**Review by leolabdev — CHANGES_REQUESTED** [review]
We now use unit tests to describe the current behavior of code, this is necessary so that all changes are expected and visible, it works like documentation. If the behavior changes, we also update our tests.

Therefore, please update the unit tests so that they do not crash.
image

**Comment by leolabdev** [comment]
@Skoivumaki > i18n should work. Note: Theres currently no way to test this since useDeleteClan is not yet implemented and probably wont even work. (API requires clan admin permissions and nothing in code checks for it atm)

there is no way to get it from api now, are you a clan admin?

**Comment by leolabdev** [comment]
I updated the tests, now we can do merge

**Pull request merged**
